<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Out-Of-Stock-Notification
 * @version     1.7
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>

<?php
$this->setPreconfiguredValue(); ?>
<?php $_product = $this->getProduct();
$notifyMail  = Mage::getStoreConfig('Outofstocknotification/general/activate_apptha_outofstock_email');
$enableOutOfStock  = Mage::getStoreConfig('Outofstocknotification/general/activate_apptha_outofstock_enable');
$enableOutOfStock = intval($enableOutOfStock);
$notifyRequest = Mage::getStoreConfig('Outofstocknotification/general/activate_apptha_outofstock_notifymes');

$storeName = Mage::getStoreConfig("general/store_information/name");
$_product = $this->getProduct();
$productId =  $_product->getId();

$productName = $_product->getName();


$productUrl = $_product->getUrlInStore();
$baseUrl = Mage::getUrl('',array('_secure'=>true));
$crtlPageUrl = $baseUrl.'outofstocknotification/index/storeNotificationProductData';

/* end outofstocknotifi */

?>
<?php $_associatedProducts = $this->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php if ($_product->isAvailable() && $_hasAssociatedProducts): ?>
    <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span>
    <?php echo $this->__('Out of stock') ?></span>
    </p>
    <?php
if($enableOutOfStock){
?>

<div class="block-body apptha-outofstock-block-body line" id='responceMesPlace'>
    <span id='contentofnotification' >
	   	 <div id="notify_conform" class="notify_conform"></div>
	     <span id="notify_message"><?php echo $notifyRequest; ?></span>
      <div id="padding_div" style="height: 33px;margin-top: 4px;" >
	     <span id="notify_error" class="line notify_error"></span>

	     <span id="notify_submit"> <b><?php echo $this->__('Email')?>:</b>
	     <input id="outofstock_email" type="text"  name="outofstock_email"  >
	     <button class="button" title="Subscribe" type="submit" onclick="return stockNotifyValidate('<?php echo $productId; ?>','')" >
	     <span><span><?php echo $this->__('Notify Me'); ?></span></span>
	     </button> <div id='ajaximageshowing' class="ajaxreloadimage" ></div>
	     <div style="display: none;color: red;font-size: 11px;margin-left: 43px;" id="outofstock_notify_error" > <?php echo $this->__('Please specify a valid Email Address'); ?><br></div>
	      </span>

	</div>
	</span>
</div>
<?php } //if out of stock endable  ?>

<?php endif; ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>
    
    <div id="groupedthanks" class="grouped-thanks"></div> 
<table class="data-table grouped-items-table" id="super-product-table">
    <col />
    <col />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <?php if ($this->getCanShowProductPrice($_product)): ?>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <?php endif; ?>
            <?php if ($_product->isSaleable()): ?>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
    <?php if ($_hasAssociatedProducts): ?>
    <?php $inc=1; foreach ($_associatedProducts as $_item): ?>
        <?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_item, $_item->getFinalPrice(), true) ?>
        <tr>
            <td><?php echo $this->htmlEscape($_item->getName()) ?></td>
            <?php if ($this->getCanShowProductPrice($_product)): ?>
            <td class="a-right">
                <?php if ($this->getCanShowProductPrice($_item)): ?>
                <?php echo $this->getPriceHtml($_item, true) ?>
                <?php echo $this->getTierPriceHtml($_item) ?>
                <?php endif; ?>
            </td>
            <?php endif; ?>
            <?php if ($_product->isSaleable()): ?>
            <td class="a-center">
            <?php if ($_item->isSaleable()) : ?>
                <input type="text" name="super_group[<?php echo $_item->getId() ?>]" maxlength="12" value="<?php echo $_item->getQty()*1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
            <?php else: ?>
                   			
							<input type="hidden" value="<?php echo $_item->getId(); ?>" id='productId' name ='productId' />
				<div style="padding: 0px;" class="block-body apptha-outofstock-block-body line"  id='responceMesPlace<?php  echo $inc ;?>'>
							    <span id='contentofnotification' >
								   	 <div id="notify_conform<?php  echo $inc ;?>" class="notify_conform"></div>
								     <span id="notify_message<?php  echo $inc ;?>"> <?php echo $notifyRequest; ?></span>
							      <div id="padding_div<?php  echo $inc ;?>" class="bmargin10 tmargin10">
								     <span id="notify_error<?php  echo $inc ;?>" class="line notify_error"></span>

								     <span id="notify_submit<?php  echo $inc ;?>"> <b><?php echo $this->__('Email')?>:</b>
								     <input id="outofstock_email<?php  echo $inc ;?>" type="text"  name="outofstock_email"  >

								     <button id='emailidofnotify<?php  echo $inc ;?>' class="align-top notify-button-blue " style="padding: 2px 6px;"
								      onclick="return stockNotifyValidate('<?php echo $_item->getId(); ?>','<?php  echo $inc ;?>','gr')">
								      <span><span><?php echo $this->__('Notify Me'); ?><span></span></button>
								     </span>
								     <div id='ajaximageshowing<?php  echo $inc ;?>' class="ajaxreloadimage" ></div>
								    <div style="display: none;color: red;font-size: 11px;" id="outofstock_notify_error<?php  echo $inc ;?>" > <?php echo $this->__('Please specify a valid Email Address'); ?></div>

								</div>
								</span>
							</div>


            <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php $inc++; endforeach; ?>
    <?php else: ?>
       <tr>
           <td colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
       </tr>
    <?php endif; ?>
    </tbody>
</table>
<script type="text/javascript">
    var crtlPageUrl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'outofstocknotification/index/storeNotificationProductData';   ?>';
Translator.add('AlreadyNotified','<?php echo $this->__('This Mail Id Already Notified'); ?>');
    decorateTable('super-product-table')
</script>
